documentation:
  - changed-files:
      - any-glob-to-all-files:
          - '**/*.md'

skip-changelog:
  - changed-files:
      - all-globs-to-all-files:
          - '!src/Publicizer/**'
          - '!icon.png'
          - '!**/*.md'
