documentation:
  - changed-files:
      - any-glob-to-all-files:
          - '**/*.md'

skip-changelog:
  - changed-files:
      - any-glob-to-all-files:
          - '{.github/**,.editorconfig,.gitignore,global.json,Publicizer.slnx,scripts/**,src/Publicizer.Tests/**}'
