changelog:
  exclude:
    authors:
      - dependabot
    labels:
      - documentation
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - "semver:major"
    - title: Features
      labels:
        - "semver:minor"
    - title: Fixes & Improvements
      labels:
        - "semver:patch"
