<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    <PackageReference Include="Microsoft.Build.Utilities.Core"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit3TestAdapter"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Publicizer\Publicizer.csproj"/>
  </ItemGroup>

</Project>