name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:

    - uses: actions/checkout@v7.0.0

    - name: Set up .NET
      uses: actions/setup-dotnet@v6.0.0
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore -warnaserror
      
    - name: Test
      run: dotnet test -c Release --no-build --no-restore
